# Generated by Django 3.0.6 on 2020-07-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbdetail',
            old_name='sername',
            new_name='username',
        ),
    ]
