# Generated by Django 3.0.6 on 2020-07-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_auto_20200701_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabledetail',
            old_name='firstname_col_name',
            new_name='first_name_col_name',
        ),
        migrations.RenameField(
            model_name='tabledetail',
            old_name='fullname_col_name',
            new_name='full_name_col_name',
        ),
        migrations.RenameField(
            model_name='tabledetail',
            old_name='lastname_col_name',
            new_name='last_name_col_name',
        ),
    ]
