# Generated by Django 3.0.6 on 2020-07-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
    ]
