# Generated by Django 3.0.6 on 2020-07-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_remove_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(null=True)),
                ('read_flag', models.BooleanField(default=True, null=True)),
                ('msg_flag', models.CharField(max_length=15, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Student')),
            ],
        ),
    ]
