# Generated by Django 3.0.6 on 2020-07-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200711_0757'),
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='rejeced_msg',
            new_name='action_msg',
        ),
        migrations.RenameField(
            model_name='complain',
            old_name='rejected_at',
            new_name='actioned_at',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='rejected',
        ),
        migrations.AddField(
            model_name='complain',
            name='action',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='complain',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_taken_by+', to='user.Member'),
        ),
        migrations.AddField(
            model_name='complain',
            name='last_edit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
