# Generated by Django 3.0.6 on 2020-07-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0003_complain_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='edited',
        ),
    ]
