# Generated by Django 3.0.6 on 2020-07-19 09:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=15)),
                ('security_question', models.CharField(max_length=40)),
                ('security_answer', models.CharField(max_length=100)),
                ('reg_datetime', models.DateField(default=django.utils.timezone.now)),
                ('activated', models.BooleanField(default=False)),
                ('activation_code', models.CharField(max_length=8)),
                ('activated_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_request', models.BooleanField(default=False)),
                ('deactivation_reason', models.TextField(blank=True, null=True)),
                ('deact_req_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member approved by member+', to='user.Member')),
                ('deact_requested_mem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Member')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_deactivated_by', to='user.Member')),
                ('reactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivated by member+', to='user.Member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberIDCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_solver_id', models.IntegerField()),
                ('next_sorter_id', models.IntegerField()),
                ('next_db_admin_id', models.IntegerField()),
                ('next_hod_id', models.IntegerField()),
                ('next_principal_id', models.IntegerField()),
                ('count_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=15)),
                ('reg_datetime', models.DateField(default=django.utils.timezone.now)),
                ('security_question', models.CharField(max_length=40)),
                ('security_answer', models.CharField(max_length=100)),
                ('complain_count', models.IntegerField(default=0)),
                ('count_date', models.DateField(default=datetime.date.today)),
                ('reactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_request', models.BooleanField(default=False)),
                ('deactivation_reason', models.TextField(blank=True, null=True)),
                ('deact_req_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deact_requested_mem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivation_requested_member', to='user.Member')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deactivated_by', to='user.Member')),
                ('reactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student reactivated by member+', to='user.Member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
