# Generated by Django 3.0.6 on 2020-06-05 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200605_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reg_datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
