# Generated by Django 3.0.6 on 2020-07-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_student_os_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='os_flag',
            new_name='oc_flag',
        ),
    ]
