# Generated by Django 3.0.6 on 2020-06-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_student_admission_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('is_hod', 'Is HOD'), ('is_db_admin', 'Is a DB Administrator'), ('is_sorter', 'Is a Sorter')]},
        ),
        migrations.AddField(
            model_name='member',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='activation_code',
            field=models.CharField(default='solver', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='solver', max_length=10),
            preserve_default=False,
        ),
    ]
