# Generated by Django 3.0.6 on 2020-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200622_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberidcount',
            old_name='next_id',
            new_name='next_db_admin_id',
        ),
        migrations.AddField(
            model_name='memberidcount',
            name='next_hod_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberidcount',
            name='next_solver_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberidcount',
            name='next_sorter_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
