# Generated by Django 3.0.6 on 2020-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200622_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('L', 'Solver'), ('R', 'Sorter'), ('D', 'DB Admin'), ('H', 'HOD')], max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='security_question',
            field=models.CharField(choices=[('1', 'In which town your mom/dad was born?'), ('2', 'What is name of your grand mother/grand father?'), ('3', 'What was your childhood nickname?'), ('4', 'which sports do you like most?')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_type',
            field=models.CharField(choices=[('FH', 'First year'), ('DS', 'Direct Second year')], max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('chemical', 'Chemical'), ('civil', 'Civil'), ('computer', 'Computer'), ('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('it', 'IT')], max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='security_question',
            field=models.CharField(choices=[('1', 'In which town your mom/dad was born?'), ('2', 'What is name of your grand mother/grand father?'), ('3', 'What was your childhood nickname?'), ('4', 'which sports do you like most?')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third'), ('4th', 'Fourth')], max_length=10),
        ),
    ]
