# Generated by Django 3.0.6 on 2020-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200623_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='security_question',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_type',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='security_question',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
