# Generated by Django 3.0.6 on 2020-06-23 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200623_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
