# Generated by Django 3.0.6 on 2020-06-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_member_activated_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='activated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
