# Generated by Django 3.0.6 on 2020-06-23 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200623_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='activated_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
