# Generated by Django 3.0.6 on 2020-06-27 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200623_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberidcount',
            name='count_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
