# Generated by Django 3.0.6 on 2020-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_memberidcount_count_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberidcount',
            name='next_principal_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
