# Generated by Django 3.0.6 on 2020-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200702_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='security_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='security_answer',
            field=models.CharField(max_length=100),
        ),
    ]
