# Generated by Django 3.0.6 on 2020-07-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200702_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deact_req_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
