# Generated by Django 3.0.6 on 2020-07-03 09:11

from django.db import migrations


class Migration(migrations.Migration):
	atomic = False
	dependencies = [
		('user', '0022_member_deact_req_datetime'),
	]

	operations = [
		migrations.RenameField(
			model_name='student',
			old_name='uid',
			new_name='sid',
		),
	]
