# Generated by Django 3.0.6 on 2020-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('user', '0023_auto_20200703_0911'),
	]

	operations = [
		migrations.AddField(
			model_name='student',
			name='deact_req_datetime',
			field=models.DateTimeField(blank=True, null=True),
		),
	]
