# Generated by Django 3.0.6 on 2020-07-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_student_deact_req_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
