# Generated by Django 3.0.6 on 2020-07-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20200704_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='deact_req_datetime',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='deact_req_datetime',
            new_name='deact_req_at',
        ),
        migrations.AddField(
            model_name='member',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member approved by member+', to='user.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='deact_req_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
