# Generated by Django 3.0.6 on 2020-07-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20200704_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member reactivated by member+', to='user.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='reativated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student reactivated by member+', to='user.Member'),
        ),
    ]
