# Generated by Django 3.0.6 on 2020-07-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20200704_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivated by member+', to='user.Member'),
        ),
    ]
