# Generated by Django 3.0.6 on 2020-07-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20200704_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_type',
        ),
    ]
