# Generated by Django 3.0.6 on 2020-07-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_student_admission_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='department',
        ),
    ]
