# Generated by Django 3.0.6 on 2020-07-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sername', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=20)),
                ('db_name', models.CharField(max_length=35)),
                ('db_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TableDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('year_col_name', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_col_name', models.CharField(blank=True, max_length=20, null=True)),
                ('student_id_col_name', models.CharField(max_length=20)),
                ('name_storage_type', models.CharField(max_length=35)),
                ('firstname_col_name', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname_col_name', models.CharField(blank=True, max_length=20, null=True)),
                ('fullname_col_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email_col_name', models.CharField(max_length=20)),
                ('contact_no_col_name', models.CharField(max_length=20)),
            ],
        ),
    ]
