# Generated by Django 3.0.6 on 2020-07-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberidcount',
            old_name='ext_solver_id',
            new_name='next_solver_id',
        ),
    ]
