# Generated by Django 3.0.6 on 2020-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='os_flag',
            field=models.CharField(default='open', max_length=5, null=True),
        ),
    ]
