# Generated by Django 3.0.6 on 2020-06-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='subject',
            field=models.CharField(default='title', max_length=35),
            preserve_default=False,
        ),
    ]
