# Generated by Django 3.0.6 on 2020-07-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redressal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='complain-redressal/')),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(default='', max_length=15)),
                ('action_msg', models.TextField(null=True)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_on_ thread+', to='user.Member')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Member')),
            ],
        ),
        migrations.AlterField(
            model_name='complain',
            name='redressal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complain.Redressal'),
        ),
    ]
