# Generated by Django 3.0.6 on 2020-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_complain_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='solve_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
