# Generated by Django 3.0.6 on 2020-07-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_auto_20200722_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='sorted',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='sorted_at',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='sorted_by',
        ),
    ]
