# Generated by Django 3.0.6 on 2020-07-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0003_auto_20200725_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='redressal',
        ),
    ]
