# Generated by Django 3.0.6 on 2020-06-04 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0004_complain_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
