# Generated by Django 3.0.6 on 2020-07-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0004_remove_complain_redressal'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='redressal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complain.Redressal'),
        ),
    ]
