# Generated by Django 3.0.6 on 2020-06-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0005_auto_20200604_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='registered_date',
            new_name='registered_datetime',
        ),
    ]
