# Generated by Django 3.0.6 on 2020-06-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0007_auto_20200604_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='student',
            new_name='complainee',
        ),
    ]
