# Generated by Django 3.0.6 on 2020-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0009_auto_20200606_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complain',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
