# Generated by Django 3.0.6 on 2020-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0011_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='category',
            field=models.CharField(choices=[('A', 'Administrative Office'), ('I', 'Infrastructure'), ('C', 'Committee/Teacher'), ('M', 'Management activites'), ('O', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complain',
            name='sub_category',
            field=models.CharField(choices=[('A', 'Admission'), ('C', 'Concession'), ('S', 'Scholarship/Freeship'), ('O', 'Other'), ('C', 'Canteen'), ('A', 'Classroom'), ('G', 'Gymnasium'), ('L', 'Library'), ('L', 'Lift'), ('P', 'Parking'), ('Y', 'Playground'), ('R', 'Practical Lab'), ('T', 'Toilets/Washrooms'), ('W', 'Workshop'), ('X', 'Xerox Office'), ('O', 'Other'), ('B', 'Branch Committees'), ('E', 'E-Cell'), ('N', 'NSS'), ('W', 'Women Development'), ('O', 'Other'), ('A', 'Attendance'), ('C', 'Cleanliness'), ('T', 'Timetable'), ('O', 'Other'), ('O', 'Other')], max_length=30),
        ),
    ]
