# Generated by Django 3.0.6 on 2020-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0012_auto_20200623_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='complain',
            name='sub_category',
            field=models.CharField(max_length=30),
        ),
    ]
