# Generated by Django 3.0.6 on 2020-07-19 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Redressal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redressal', models.TextField(blank=True, null=True)),
                ('redressal_file', models.FileField(blank=True, null=True, upload_to='redressal/')),
                ('redressed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(default='', max_length=15)),
                ('action_msg', models.TextField(null=True)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_on_ thread+', to='user.Member')),
                ('redressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('sub_category', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('complain_count', models.IntegerField(default=0)),
                ('note_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('solver', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
                ('redressal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threads.Redressal')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Category')),
            ],
        ),
    ]
