# Generated by Django 3.0.6 on 2020-07-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redressal',
            old_name='redressed_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='redressal',
            old_name='redressed_by',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='redressal',
            old_name='redressal',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='redressal',
            name='redressal_file',
        ),
        migrations.AddField(
            model_name='redressal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='thread-redressal/'),
        ),
    ]
