# Generated by Django 3.0.6 on 2020-07-27 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('threads', '0002_auto_20200722_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='solving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solver_member+', to='user.Member'),
        ),
    ]
