# Generated by Django 3.0.6 on 2020-07-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20200716_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='name',
        ),
    ]
