# Generated by Django 3.0.6 on 2020-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20200716_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
